# global configs
Global:
  mode: evaluation    # evaluation, inference
  category: detection
  output_dir: ./output/
  save_interval: 1
  eval_during_train: True
  eval_interval: 1
  epochs: 360
  print_batch_step: 10
  use_visualdl: False
  # used for static mode and model export
  image_shape: [3, 640, 640]
  save_inference_dir: ./inference

# model architecture

Model:
  name: PPYOLOE-s
  backend: powervr_grpc   #clas_sim, paddle, powervr
  head_ops:
    - ReOutputsKey:
        bboxes: tvm_infer_0_out_0.bin
        scores: tvm_infer_0_out_1.bin
    - Reshape:
        bboxes: [1, 4, 8400]
        scores: [1, 80, 8400]
    - Transpose:
        bboxes: [0, 2, 1]
        scores: [0, 2, 1]
    - PPYoloE:
        image_size: [640, 640]
    - HardNMS:
        iou_threshold: 0.6
        threshold: 0.01

  PowerVR_gRPC:
    #pvr_server: 192.168.10.4
    pvr_server: 10.80.49.46
    input_name: image
    output_shape: [1000]

# data loader for train and eval
DataLoader:
  Eval:
    dataset: 
      name: COCODataset
      image_dir: C:\development\paddle\PaddleDetection\tools\dataset\coco\val2017
      annotation_path: C:\development\paddle\PaddleDetection\tools\dataset\coco\annotations\instances_val2017.json
      transform_ops:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - ResizeImage:
            size: 640
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage: {}
      num_image: 5
    sampler:
      name: BatchSampler
      batch_size: 1
      drop_last: False
      shuffle: False
    loader:
      reserved: None
Metric:
  image_size: [640, 640]
  dataset: C:\development\paddle\PaddleDetection\tools\dataset\coco\annotations\instances_val2017.json